### ISSUE TITLE
Usuário inexistente/senha incorreta

### ISSUE THREAD

**Issue by treezao** [gildonei/nfse-pmf#1]
Olá,

Estou tentando utilizar sua biblioteca mas sempre dá o seguinte erro na parte de autenticação:

NFSeRequestException: Usuário inexistente ou senha inválida

As credenciais aparentemente estão certas, CMC, senha em md5 (uppercase), e client_id e client_secret. Até tentei emitir novos ids e secrets mais ainda assim o erro ocorre... Tem ideia do que pode ser o erro?

A senha é a mesma que uso para acessar o sistema web da PMF...

**Comment by gildonei** [comment]
Boa noite. Você chegou a verificar se as credenciais que está usando são do
ambiente de produção ou sandbox?

Em qui., 21 de nov. de 2024 19:55, treezao ***@***.***>
escreveu:

**Comment by treezao** [comment]
Então, de acordo com o manual da PMF, client_id e client_secret são únicos para ambos. 
E o usuário/senha estou usando um único para ambos os ambientes.
De qualquer forma eu testei tanto no modo de homologação quanto no de produção da sua biblioteca, e o resultado é o mesmo =/.

Estou rodando a biblioteca no XAMPP. Para logar no site é necessário ter uma certificação digital, será que pode ser algo relacionado a isso?

**Comment by gildonei** [comment]
Sobre o login e senha, normalmente sim. Mas já tive clientes que as
credenciais eram diferentes para os ambientes.

Sobre o SSL é interessante rodar com certificado mesmo que auto assinado.

No xampp tem um instalador (.bat) que roda um certificado auto assinado
para seu usado em localhost.  Vc tem apenas que configurar o cacurl.info no
php.ini com o arquivo cacert.pem do apache que vc pode baixar na internet.
Só pesquisar pelo nome do arquivo para download

Em qui., 21 de nov. de 2024 21:00, treezao ***@***.***>
escreveu:

**Comment by treezao** [comment]
Adicionei o SSL, aparentemente está funcionando, consigo acessar o site local com HTTPS e nada...

**Comment by gildonei** [comment]
O usuário não vai MD5, apenas a senha

Em qui., 21 de nov. de 2024 22:16, treezao ***@***.***>
escreveu:

**Comment by gildonei** [comment]
O MD5 da senha tem de ser em uppercase tb

Em sex., 22 de nov. de 2024 14:44, Gildonei Mendes Anacleto Junior <
***@***.***> escreveu:

**Comment by treezao** [comment]
Sim,
usuário é o CMC normal, e a senha em MD5 uppercase., já estava fazendo isso.

**Comment by gildonei** [comment]
Além disso seria apenas o clientId e clientSecret para realizar a
autenticação

Em sex., 22 de nov. de 2024 14:57, treezao ***@***.***>
escreveu:

**Comment by gildonei** [comment]
Chegou a dar uma olhada no arquivo de exemplo da autenticação?

Em sex., 22 de nov. de 2024 14:59, Gildonei Mendes Anacleto Junior <
***@***.***> escreveu:

**Comment by treezao** [comment]
Sim, no momento estou usando ele diretamente, só alterei o arquivo de credenciais de acordo com o indicado. Por isso que estou com dificuldade de entender pq está dando errado T-T.

**Comment by gildonei** [comment]
Sugiro solicitar uma revisão no seu clientId e secret. E testar a confecção
em ambos os ambientes.

Se ainda assim não der certo. Sugiro enviar e-mail para a PMF e validar
suas credenciais.

Em sex., 22 de nov. de 2024 15:08, treezao ***@***.***>
escreveu:

**Comment by treezao** [comment]
Olá, só para fechar o problema, a culpa era de um espaço em branco após o último caractere da senha em MD5... não enxergava de jeito nenhum isso... Depois que removi isso a autenticação deu certo.

Agora vou partir para o desenvolvimento. Obrigado!
